#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from .layout import layout

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6'
__CHEETAH_versionTuple__ = (3, 2, 6, 'final', 0)
__CHEETAH_genTime__ = 1604776366.4158664
__CHEETAH_genTimestamp__ = 'Sat Nov  7 19:12:46 2020'
__CHEETAH_src__ = 'compressed_repoclosure.tmpl'
__CHEETAH_srcLastModified__ = 'Sat Nov  7 19:12:40 2020'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class compressed_repoclosure(layout):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(compressed_repoclosure, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def mainContent(self, **KWS):



        ## CHEETAH: generated from #def mainContent() at line 3, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<div class="row">
  <div class="col">
    <table class="table table-hover table-sm table-bordered">
      <thead class="thead-light">
        <th scope="col">#</th>
        <th scope="col">Unresolved dependencies</th>
        <th scope="col">Packages</th>
      </thead>
      <tbody>
''')
        cnt = 1
        for unresolved, packages in VFFSL(SL,"bad_packages",True): # generated from line 14, col 9
            write('''          <tr>
            <th scope="row">''')
            _v = VFFSL(SL,"cnt",True) # '$cnt' on line 16, col 29
            if _v is not None: write(_filter(_v, rawExpr='$cnt')) # from line 16, col 29.
            write('''</th>
            <td><pre>''')
            _v = VFFSL(SL,"unresolved",True) # '$unresolved' on line 17, col 22
            if _v is not None: write(_filter(_v, rawExpr='$unresolved')) # from line 17, col 22.
            write('''</pre></td>
            <td><pre>''')
            _v = VFFSL(SL,"packages",True) # '$packages' on line 18, col 22
            if _v is not None: write(_filter(_v, rawExpr='$packages')) # from line 18, col 22.
            write('''</pre></td>
          </tr>
''')
            cnt = VFFSL(SL,"cnt",True) + 1
        write('''      </tbody>
    </table>
  </div>
</div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def links(self, **KWS):



        ## CHEETAH: generated from #def links at line 27, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<ul class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="index.html">Index</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="''')
        _v = VFFSL(SL,"normal",True) # '$normal' on line 33, col 31
        if _v is not None: write(_filter(_v, rawExpr='$normal')) # from line 33, col 31.
        write('''">Normal report</a>
  </li>
</ul>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_compressed_repoclosure = 'writeBody'

## END CLASS DEFINITION

if not hasattr(compressed_repoclosure, '_initCheetahAttributes'):
    templateAPIClass = getattr(compressed_repoclosure,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(compressed_repoclosure)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=compressed_repoclosure()).run()


